lang = 'rust'

[snippets.derive]
body = '''
#[derive(Debug, Default, Clone, $1)]
'''

[snippets.therad_scope]
body = '''
crossbeam_utils::thread::scope(|scope| {
    ${1:element}
    scope.spawn(move |_| {
        ${2:element}
    });
})
.unwrap();
'''

[snippets.FromStr]
body = '''
impl FromStr for $1 {
    type Err = anyhow::Error;

    fn from_str(s: &str) -> anyhow::Result<Self> {
        todo!();
    }
}
'''

[snippets.sleep]
body = '''
std::thread::sleep(std::time::Duration::from_millis(${1:n)}));
'''

[snippets.rr]
body = '''
r#"$1"#
'''

[snippets.inspect]
body = '''
.inspect(|e| {
    dbg!(e);
})
'''

[snippets.main]
body = '''
fn main() -> anyhow::Result<()> {
  $1

  Ok(())
}
'''

[snippets.result]
body = '''
anyhow::Result<$1>
'''

[snippets.bail]
body = '''
anyhow::bail!($1)
'''

[snippets.tests]
body = '''
#[cfg(test)]
mod tests {
    #[test]
    fn test() {
      $1
    }
}
'''
