lang = 'typescript'

[snippets.voidfn]
body = '''
() => {}
'''

[snippets.gcd]
body = '''
const gcd = (a: number, b: number) => {
return b == 0 ? a : gcd(b, a % b)
};
'''

[snippets.factional]
body = '''
const factional = (n: number) => {
return n <= 1 ? 1 : n * factional(n - 1);
};
'''
