
[tasks.echo]
script = [
'''
echo okoo
'''
]

[tasks.add-wasm]
script = [
'''
rustup update
rustup target add wasm32-unknown-unknown --toolchain nightly
cargo install wasm-pack
'''
]

[tasks.add-python-mac]
script = [
'''
brew install pyenv
curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
poetry completions zsh > ~/.zfunc/_poetry
'''
]

[tasks.add-python-linux]
script = [
'''
curl https://pyenv.run | bash
curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
poetry completions zsh > ~/.zfunc/_poetry
'''
]

[tasks.up-rust]
script = [
'''
rustup update
rustup component add rls rust-analysis rust-src ;: LPS
rustup component add clippy
cargo install cargo-edit ;: subcommand `add`, `rm`, `upgrade`
cargo install --force cargo-make
'''
]

[tasks.up-nodeapp]
script = [
'''
npm i -g firebase-tools
'''
]

[tasks.link-ssh]
script = [
'''
mkdir -p ~/.ssh
ln -svf ~/Gdrive/ssh/common/config ~/.ssh/config
ln -svf ~/Gdrive/ssh/common/config.d ~/.ssh/config.d
'''
]
