[tasks.add-brew]
script = [
'''
git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew
mkdir ~/.linuxbrew/bin
ln -s ../Homebrew/bin/brew ~/.linuxbrew/bin
eval $(~/.linuxbrew/bin/brew shellenv)
'''
]

[tasks.add-z]
dependencies = ["add-zsh", "add-zplug"]

[tasks.add-zplug]
script = [
'''
curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
export ZPLUG_HOME=$HOME/.zplug
source $ZPLUG_HOME/init.zsh
source ~/.zshrc
zplug install
chmod -R 755 $ZPLUG_HOME
source ~/.zshrc
'''
]

[tasks.add-zsh]
script = [
'''
#!/bin/sh
: ### install zsh
brew install zsh

: ### install zplugin
sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zplugin/master/doc/install.sh)"
brew install svn ;: for zplugin
'''
]


[tasks.add-vim]
script = [
'''
brew install neovim
bash setup.d/dein.sh
ln -s ~/dotfiles/nvim ~/.config/nvim
vi +":call dein#install()" +qa
'''
]

[tasks.add-python-mac]
script = [
'''
brew install pyenv
curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
poetry completions zsh > ~/.zfunc/_poetry
'''
]

[tasks.add-python-linux]
script = [
'''
curl https://pyenv.run | bash
curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
poetry completions zsh > ~/.zfunc/_poetry
'''
]

[tasks.up-rust]
script = [
'''
rustup update
rustup component add rls rust-analysis rust-src ;: LPS
rustup component add clippy
cargo install cargo-edit ;: subcommand `add`, `rm`, `upgrade`
cargo install --force cargo-make
'''
]
