[tasks.add-brew]
script = [
'''
git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew
mkdir ~/.linuxbrew/bin
ln -s ../Homebrew/bin/brew ~/.linuxbrew/bin
eval $(~/.linuxbrew/bin/brew shellenv)
'''
]

[tasks.add-zsh]
script = [
'''
: ### install zsh
brew install zsh

: ### install zplugin
sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zplugin/master/doc/install.sh)"
brew install svn ;: for zplugin
sudo chsh -s "$(command -v zsh)" "${USER}"
'''
]

[tasks.add-vim]
script = [
'''
brew install neovim
bash setup.d/dein.sh
nvim +":call dein#install()" +qa
'''
]

[tasks.add-coc]
script = [
'''
vi +":CocInstall coc-rls" +qa ;: Rust
vi +":CocInstall coc-python" +qa
vi +":CocInstall coc-tsserver" +qa ;: TypeScript
vi +":CocInstall coc-html" +qa
vi +":CocInstall coc-css" +qa
vi +":CocInstall coc-yaml" +qa
vi +":CocInstall coc-vetur" +qa ;: Vue
vi +":CocInstall coc-solargraph" +qa ;: Ruby
vi +":CocInstall coc-emoji" +qa ;: for Markdown file only
'''
]

[tasks.add-dev]
script = [
'''
brew update
brew install git
brew install exa ;: alternative for `ls`
brew install sl ;: alternative for `ls`
brew install fuyutarow/commad/commad ;: alternative for `cd`
brew install lolcat ;: alternative for `cat`
brew install colordiff ;: alternative for `diff`
brew install translate-shell ;: `trans`
'''
]

[tasks.add-node]
script = [
'''
curl -L git.io/nodebrew | perl - setup
# export PATH=$HOME/.nodebrew/current/bin:$PATH
nodebrew install latest
nodebrew use latest
npm install -g yarn
npm install -g ts-node typescript
'''
]

[tasks.add-python]
script = [
'''
brew install pyenv poetry pipx
poetry completions zsh > ~/.zfunc/_poetry
'''
]

[tasks.add-python-mac]
script = [
'''
brew install pyenv
curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
poetry completions zsh > ~/.zfunc/_poetry
'''
]

[tasks.add-python-linux]
script = [
'''
curl https://pyenv.run | bash
curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
poetry completions zsh > ~/.zfunc/_poetry
'''
]

[tasks.up-rust]
script = [
'''
rustup update
rustup component add rls rust-analysis rust-src ;: LPS
rustup component add clippy
cargo install cargo-edit ;: subcommand `add`, `rm`, `upgrade`
cargo install --force cargo-make
'''
]

[tasks.link-wsl]
script = [
'''
ln -svf /mnt/c/Users/fuyutarow/Desktop/ ~
ln -svf /mnt/c/Users/fuyutarow/Downloads/ ~
ln -svf /mnt/c/Users/fuyutarow/Gdrive/ ~
ln -svf /mnt/c/Users/fuyutarow/Gdrive/ssh ~/.ssh
'''
]

[tasks.add-scoop]
script_runner = "powershell.exe"
script_extension = "ps1"
script = [
'''
Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
scoop bucket add extras
'''
]

[tasks.add-chrome]
script_runner = "powershell.exe"
script_extension = "ps1"
script = [
'''
scoop install chromium googlechrome googlechrome-beta googlechrome-dev googlechrome-canary
'''
]

[tasks.add-vscode]
script_runner = "powershell.exe"
script_extension = "ps1"
script = [
'''
scoop install vscode
'''
]
# usage
# =====
# ```
# $ code
# ```
