# [[plugins]]
# repo = 'google/vim-codefmt'

# [[plugins]]
# repo = 'google/vim-codefmt'
# hook_post_update = '''
  # augroup autoformat_settings
    # autocmd FileType bzl AutoFormatBuffer buildifier
    # autocmd FileType c,cpp,proto,javascript AutoFormatBuffer clang-format
    # autocmd FileType dart AutoFormatBuffer dartfmt
    # autocmd FileType go AutoFormatBuffer gofmt
    # autocmd FileType gn AutoFormatBuffer gn
    # autocmd FileType html,css,json AutoFormatBuffer js-beautify
    # autocmd FileType java AutoFormatBuffer google-java-format
    # autocmd FileType python AutoFormatBuffer yapf
    # " Alternative: autocmd FileType python AutoFormatBuffer autopep8
  # augroup END
  # nnoremap <S-f> :FormatCode<CR>

  # autocmd BufRead,BufNewFile *.ts set filetype=typescript
  # autocmd BufRead,BufNewFile *.tsx set filetype=typescript
  # autocmd BufNewFile,BufRead *.{html,htm,vue*} set filetype=html
# '''


# [[plugins]]
# repo = 'sebastianmarkow/deoplete-rust'
# on_ft = 'rust'
# depends = ['deoplete.nvim']
# hook_source = '''
  # let g:deoplete#sources#rust#racer_binary="expand('~/.cargo/bin/racer')"
  # let g:deoplete#sources#rust#rust_source_path='{$(rustc --print sysroot)/lib/rustlib/src/rust/src}'
  # let $RUST_SRC_PATH='{$(rustc --print sysroot)/lib/rustlib/src/rust/src}'
  # let g:deoplete#sources#rust#show_duplicates=1
  # let g:deoplete#sources#rust#disable_keymap=1
  # nmap <buffer> gd <plug>DeopleteRustGoToDefinitionDefault
  # nmap <buffer> K  <plug>DeopleteRustShowDocumentation
# '''

# [[plugins]]
# repo = 'racer-rust/vim-racer'
# on_ft = 'rust'
# hook_source = '''
  # let g:racer_cmd = "expand('~/.cargo/bin/racer')"
  # let $RUST_SRC_PATH='{$(rustc --print sysroot)/lib/rustlib/src/rust/src}'
# '''
