$pdf_mode = 4;
$out_dir = 'build';
$aux_dir = 'build';
$emulate_aux = 1;

$lualatex = 'lualatex -synctex=1 -interaction=nonstopmode -halt-on-error %O %S';

$clean_ext = 'bbl bcf blg fdb_latexmk fls nav run.xml snm synctex.gz toc vrb';
$pdf_previewer = 'open -a Preview';
