[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'leico/autodate.vim'

[[plugins]]
repo = 'kana/vim-smartinput'

[[plugins]]
repo = 'neoclide/coc.nvim'
build = './install.sh nightly'
hook_add = 'source ~/.config/nvim/coc.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = '''
let g:unite_enable_start_insert=1
let g:unite_source_history_yank_enable =1
let g:unite_source_file_mru_limit = 200
nnoremap <silent> ,uy :<C-u>Unite history/yank<CR>
nnoremap <silent> ,ub :<C-u>Unite buffer<CR>
nnoremap <silent> ,uf :<C-u>UniteWithBufferDir -buffer-name=files file<CR>
nnoremap <silent> ,ur :<C-u>Unite -buffer-name=register register<CR>
nnoremap <silent> ,uu :<C-u>Unite file_mru buffer<CR>
'''

# dev utils
# =========

[[plugins]] # helper for paren complement
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
noremap ,t :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'scrooloose/nerdcommenter'
hook_add = '''
let g:NERDSpaceDelims=1
let g:NERDDefaultAlign='left'
noremap ,, :call NERDComment("n", "Uncomment")<CR>
noremap .. :call NERDComment("n", "Comment")<CR>
noremap .A :call NERDComment("n", "Append")<CR>
'''


# color scheme
# ============

[[plugins]]
repo = 'cocopon/pgmnt.vim,'

[[plugins]]
repo = 'cocopon/iceberg.vim'
depends = 'cocopon/pgmnt.vim'
hook_add = '''
syntax on
colorscheme iceberg
'''
