// vendor-deps — generate agents/hooks/vendor/deps.{js,d.ts}: zod and neverthrow's fromThrowable as
// ONE committed bundle, so every file in this repo — hooks included — imports zod the same way.
// Consumer: `mise run vendor:deps` (write) and `mise run vendor:deps:check` (lint gate).
//
// WHY A BUNDLE. Hooks run before `bun install` (a fresh clone, a bun.lock change not yet
// installed) and fail closed, so they cannot import from node_modules. Without this file the repo
// had two ways to read external data: zod outside hooks and hand-written `typeof` narrowing
// inside, plus a bare `JSON.parse` wherever someone reached for it. The bundle is built from the
// exact packages pinned in package.json/bun.lock; its types are the same packages' own `.d.ts`,
// re-exported, so nothing is asserted by hand.
//
// Exit: 0 written / up to date · 1 --check found drift (run `mise run vendor:deps`) · 2 FATAL.
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { cli } from "cleye";
import { fromThrowable } from "neverthrow";

const ROOT = join(import.meta.dir, "..");
const OUT_DIR = join(ROOT, "agents", "hooks", "vendor");
const ENTRY =
  'export * from "zod";\nexport { fromThrowable } from "neverthrow";\n';
// The types of exactly what ENTRY exports, from the packages themselves (resolved at type-check
// time from node_modules, where the bundle's sources also come from).
const DTS = `// GENERATED by scripts/vendor-deps.ts — do not edit. Types of deps.js: the pinned packages' own.\n${ENTRY}`;

const rejectPrototypeFlag = (type: string, flag: string): void => {
  if (type === "unknown-flag" && flag === "__proto__") {
    console.error(`FATAL: unknown option '--${flag}'`);
    process.exit(2);
  }
};
const argv = cli(
  {
    name: "vendor-deps",
    strictFlags: true,
    ignoreArgv: rejectPrototypeFlag,
    parameters: [],
    help: {
      description:
        "Generate (or --check) the committed zod+neverthrow bundle in agents/hooks/vendor.",
    },
    flags: {
      check: {
        type: Boolean,
        default: false,
        description: "compare only; exit 1 on drift",
      },
    },
  },
  undefined,
  Bun.argv.slice(2),
);

if (argv._.length > 0) {
  console.error(
    `FATAL: unexpected argument: ${argv._[0]} (this command takes none)`,
  );
  process.exit(2);
}

function version(
  pkg: string,
): { ok: true; value: string } | { ok: false; error: string } {
  const result = fromThrowable(() =>
    readFileSync(join(ROOT, "node_modules", pkg, "package.json"), "utf8"),
  )();
  if (result.isErr())
    return {
      ok: false,
      error: `cannot read ${pkg}'s version from node_modules`,
    };
  const text = result.value;
  const m = text.match(/"version"\s*:\s*"([^"]+)"/u);
  if (m?.[1] === undefined)
    return {
      ok: false,
      error: `cannot read ${pkg}'s version from node_modules`,
    };
  return { ok: true, value: m[1] };
}

const entryPath = join(ROOT, "__vendor_deps_entry__.ts");
const built = await Bun.build({
  entrypoints: ["virtual:vendor-deps"],
  target: "bun",
  format: "esm",
  minify: true,
  plugins: [
    {
      name: "vendor-deps-entry",
      setup(b) {
        // The entry exists only in memory; placing it at the repo root makes its imports resolve
        // from the repo's node_modules.
        b.onResolve({ filter: /^virtual:vendor-deps$/u }, () => ({
          path: entryPath,
          namespace: "file",
        }));
        b.onLoad({ filter: /__vendor_deps_entry__\.ts$/u }, () => ({
          contents: ENTRY,
          loader: "ts",
        }));
      },
    },
  ],
});
if (!built.success || built.outputs[0] === undefined) {
  console.error(`FATAL: bundle failed: ${built.logs.map(String).join("; ")}`);
  process.exit(2);
}
const zodVersion = version("zod");
if (!zodVersion.ok) {
  console.error(`FATAL: ${zodVersion.error}`);
  process.exit(2);
}
const neverthrowVersion = version("neverthrow");
if (!neverthrowVersion.ok) {
  console.error(`FATAL: ${neverthrowVersion.error}`);
  process.exit(2);
}
const banner = `// GENERATED by scripts/vendor-deps.ts from zod@${zodVersion.value} and neverthrow@${neverthrowVersion.value} — do not edit; run \`mise run vendor:deps\`.\n`;
const js = banner + (await built.outputs[0].text());

const files = [
  { path: join(OUT_DIR, "deps.js"), text: js },
  { path: join(OUT_DIR, "deps.d.ts"), text: DTS },
];
const drift = files.filter((f) => {
  const have = Bun.file(f.path);
  return have.size === 0 || readFileSync(f.path, "utf8") !== f.text;
});

if (argv.flags.check) {
  if (drift.length === 0) {
    console.log("vendor-deps: up to date");
    process.exit(0);
  }
  console.log(
    `vendor-deps: DRIFT in ${drift.map((f) => f.path.slice(ROOT.length + 1)).join(", ")} — the committed bundle is not what the pinned packages build to; run \`mise run vendor:deps\` and commit the result`,
  );
  process.exit(1);
}
for (const f of drift) await Bun.write(f.path, f.text);
console.log(
  drift.length === 0
    ? "vendor-deps: up to date"
    : `vendor-deps: wrote ${drift.map((f) => f.path.slice(ROOT.length + 1)).join(", ")}`,
);
