// script-check.ts — mechanical floor for house Bun TypeScript scripts (writing-bun-scripts).
// Run: bun script-check.ts <file.ts|file.sh ...>   Consumer: agent (verdict lines).
// Exit: 0 clean (WARNs allowed — they inform, they do not gate) / 1 any FAIL / 2 fatal.
//
// THIS IS NOT A SEMANTIC CHECK. It greps structure only, with declared heuristics
// (per-call windows, line-based comment stripping). It cannot judge: whether the declared
// consumer/envelope is right, exit-code discipline, whether a bash shim was classified
// correctly, timeout values, or test adequacy — those are BG1–BG4 judgment.
//
// A `.sh` path skips every TS check below and runs ONLY the BG0 shim-marker check.
//
// Checks (owner: writing-bun-scripts SKILL.md gates; facts: references/bun-facts.md):
//   F1  node shebang            — bun honors `#!/usr/bin/env node` and would exec node
//   W8  any other shebang       — BG1: shebang only on binary-substituted fixtures
//   F2  CommonJS require        — scripts are ESM only (top-level await incompatible)
//   F3  external import         — bare import FAIL unless an ancestor package.json+bun.lock
//                                 (BG3 graduation, resolved on the file's REALPATH) declares it
//                                 at an EXACT version; ALWAYS FAIL inside hooks/ (they run
//                                 before any install); pinned inline import WARN (cwd trap);
//                                 computed dynamic WARN
//   F5  Cleye boundary unguarded — every cli()/command() has strictFlags plus a local
//                                 ignoreArgv prototype guard before type-flag mutation
//   F8  legacy/raw argv parsing — parseArgs(), raw argv without cli(), or direct typeFlag()
//                                 unless the exact argv-forwarding marker declares an exception
//   W11 typed-parser Number     — a Number flag with no null check: bad input yields null, not
//                                 a throw, so the failure is silent
//   F13 raw String flag parser  — missing flag values become ""; use a throwing parser
//   F4  child_process exec()    — string-shell; use Bun.$ or spawn array-form
//   W5  unbounded spawn         — per-call: no timeout:/signal: in the call window and no
//                                 `// bounded: <reason>` beside it
//   W6  setTimeout + kill       — hand-rolled timeout; native Bun.spawn timeout: exists
//   W7  unpinned bunx           — bunx staleness is real; pin pkg@x.y.z
//   W9  .killed as detector     — true after a clean exit; use AbortSignal.timeout + aborted
//   W10 sequential pipe drain   — stdout-then-stderr deadlocks; drain via Promise.all
//   F7  .sh with no shim marker — BG0: a surviving `.sh` carries `# shim: <class>` or is
//                                 content-detected `vendored` (an external tool's own header)

import { existsSync, readFileSync, realpathSync } from "node:fs";
import { dirname, join } from "node:path";
import { cli } from "cleye";

let failures = 0;
let warnings = 0;

function fail(file: string, message: string): void {
  process.stdout.write(`FAIL ${file}: ${message}\n`);
  failures += 1;
}

function warn(file: string, message: string): void {
  process.stdout.write(`WARN ${file}: ${message}\n`);
  warnings += 1;
}

// Split tokens so this file's own source does not trip its own scans (self-scan guard).
const BUNX = "bun" + "x";
const KILLED = "kill" + "ed";
const BUNX_PATTERN = new RegExp(`\\b${BUNX}\\b`);

// --- F7: BG0 shim marker for surviving .sh files -------------------------------------------
// A `# shim: <class>` comment line, any of the four declared classes. `vendored` is the one
// EXEMPT class: its own tool overwrites the file, so a written marker would not survive —
// exemption is read from the file's OWN CONTENT (a vendor header), never a path allowlist.
const SHIM_CLASSES = [
  "bootstrap",
  "hook-entry",
  "exec-wrapper",
  "vendored",
] as const;
const SHIM_LINE = /^\s*#\s*shim:\s*(\S+)\s*$/m;
const VENDOR_HEADER =
  /\b(?:managed by|generated by|installed by|auto-?generated|do not edit)\b/i;

function checkShellFile(file: string, source: string): void {
  // .match(), not RegExp.prototype.exec() — the literal token "exec(" would trip this
  // file's own F4 self-scan (it shares the file with an unrelated `child_process` mention).
  const match = source.match(SHIM_LINE);
  if (match) {
    const declared = match[1] ?? "";
    if ((SHIM_CLASSES as readonly string[]).includes(declared)) return;
    fail(
      file,
      `'# shim: ${declared}' is not a declared class (${SHIM_CLASSES.join("|")}) (BG0)`,
    );
    return;
  }
  if (VENDOR_HEADER.test(source)) {
    warn(
      file,
      "no `# shim:` marker, but a vendor header was detected — treated as the vendored exemption (BG0); a written marker would not survive the tool's own overwrite",
    );
    return;
  }
  fail(
    file,
    `no \`# shim: <${SHIM_CLASSES.join("|")}>\` marker (BG0) — a surviving .sh needs a declared shim class, or a vendor header if the exemption applies`,
  );
}

const IMPORT_SPECIFIER =
  /(?:^|\s)(?:import|export)\s+[^"'()]*?from\s+["']([^"']+)["']|(?:^|\s)import\s+["']([^"']+)["']|import\s*\(\s*["'`]([^"'`$]+)["'`]\s*\)/g;
const COMPUTED_DYNAMIC_IMPORT = /import\s*\(\s*(?:`[^`]*\$\{|[A-Za-z_$])/;
const BOUNDED_NOTE = /\/\/\s*bounded:\s*\S/;

function classifySpecifier(
  spec: string,
): "builtin" | "relative" | "pinned" | "bare" {
  if (spec.startsWith("node:") || spec.startsWith("bun:") || spec === "bun")
    return "builtin";
  if (spec.startsWith(".") || spec.startsWith("/")) return "relative";
  // pinned: name@range or @scope/name@range (an @ after the first character)
  return spec.slice(1).includes("@") ? "pinned" : "bare";
}

// --- BG3 graduation resolution -------------------------------------------------------------
// A bare specifier is legal when a graduation project GOVERNS the file: the nearest ancestor
// package.json (walking the file's REALPATH, because skills are symlinked into ~/.claude/skills
// and Bun resolves through the link) that has a sibling bun.lock, declaring the dep at an EXACT
// version. A range pin (^ ~ * x) is not a pin — PINNED-OR-ABSENT.
type Graduation = { root: string; deps: Map<string, string> };
const graduationCache = new Map<string, Graduation | null>();

function findGraduation(fromFile: string): Graduation | null {
  let directory = dirname(realpathSync(fromFile));
  const seen: string[] = [];
  for (;;) {
    const cached = graduationCache.get(directory);
    if (cached !== undefined) {
      for (const d of seen) graduationCache.set(d, cached);
      return cached;
    }
    seen.push(directory);
    const manifest = join(directory, "package.json");
    if (existsSync(manifest) && existsSync(join(directory, "bun.lock"))) {
      let deps = new Map<string, string>();
      try {
        const parsed = JSON.parse(readFileSync(manifest, "utf8")) as {
          dependencies?: Record<string, string>;
          devDependencies?: Record<string, string>;
        };
        deps = new Map(
          Object.entries({ ...parsed.dependencies, ...parsed.devDependencies }),
        );
      } catch {
        deps = new Map();
      }
      const found: Graduation = { root: directory, deps };
      for (const d of seen) graduationCache.set(d, found);
      return found;
    }
    const parent = dirname(directory);
    if (parent === directory) break;
    directory = parent;
  }
  for (const d of seen) graduationCache.set(d, null);
  return null;
}

const EXACT_VERSION = /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/;

// A graduation project licenses bare imports only for code that STAYS inside it. Two classes
// leave and must remain zero-dep, because where they run there is no lockfile and no install:
//   1. hooks/ — run on every harness event, before any `mise run deps` on this machine;
//   2. any tree marked with a `.zero-dep` file — skills that are mirrored, persisted, or
//      degit-copied into other people's repos, and `templates/` shipped into deliverables.
// The marker is the escape hatch for (2) because "does this get distributed?" is not something
// a floor can infer from a path.
function zeroDepReason(file: string): string | null {
  const path = realpathSync(file).replaceAll("\\", "/");
  if (/(^|\/)(hooks|templates)\//.test(path)) {
    return "it lives under hooks/ or templates/ — that code runs where no install has happened";
  }
  let directory = dirname(path);
  for (;;) {
    if (existsSync(join(directory, ".zero-dep"))) {
      return `${directory}/.zero-dep marks this tree as distributed — it runs outside this repo's lockfile`;
    }
    const parent = dirname(directory);
    if (parent === directory) return null;
    directory = parent;
  }
}

// Line-based comment stripping: drops // lines and /* ... */ block interiors (heuristic —
// a string literal containing comment markers can confuse it; acceptable for a floor).
function codeLines(source: string): string {
  const kept: string[] = [];
  let inBlock = false;
  for (const line of source.split("\n")) {
    let text = line;
    if (inBlock) {
      const close = text.indexOf("*/");
      if (close === -1) continue;
      text = text.slice(close + 2);
      inBlock = false;
    }
    if (/^\s*\/\//.test(text)) continue;
    const open = text.indexOf("/*");
    if (open !== -1 && !text.slice(open + 2).includes("*/")) {
      text = text.slice(0, open);
      inBlock = true;
    }
    kept.push(text);
  }
  return kept.join("\n");
}

// F8 needs executable tokens, not examples embedded in diagnostics or tests. This is deliberately
// a lexical floor rather than a TS parser: strings, template text, comments, and regex literals are
// blanked while executable identifiers remain. Template ${...} bodies stay executable and recurse
// through nested templates. The slash heuristic is intentionally conservative; a false positive is
// a floor finding to review, never an automatic source rewrite.
function executableCode(source: string): string {
  const output = Array.from(source, (character) =>
    character === "\n" ? "\n" : " ",
  );
  const reveal = (index: number): void => {
    output[index] = source[index] ?? " ";
  };
  const previousExecutable = (before: number): string => {
    for (let index = before - 1; index >= 0; index -= 1) {
      const character = output[index] ?? "";
      if (!/\s/.test(character)) return character;
    }
    return "";
  };
  const regexStart = (index: number): boolean => {
    const previous = previousExecutable(index);
    return previous === "" || /[=([{,:;!?&|^~<>+*%]/.test(previous);
  };
  const skipQuoted = (start: number, quote: '"' | "'"): number => {
    let index = start + 1;
    while (index < source.length) {
      const character = source[index] ?? "";
      if (character === "\\") {
        index += 2;
        continue;
      }
      index += 1;
      if (character === quote) break;
    }
    return index;
  };
  const skipRegex = (start: number): number => {
    let index = start + 1;
    let inClass = false;
    while (index < source.length) {
      const character = source[index] ?? "";
      if (character === "\\") {
        index += 2;
        continue;
      }
      if (character === "[") inClass = true;
      if (character === "]") inClass = false;
      index += 1;
      if (character === "/" && !inClass) {
        while (/[A-Za-z]/.test(source[index] ?? "")) index += 1;
        break;
      }
    }
    return index;
  };

  let scanTemplate: (start: number) => number;
  const scanCode = (start: number, stopAtClosingBrace: boolean): number => {
    let braceDepth = 0;
    let index = start;
    while (index < source.length) {
      const character = source[index] ?? "";
      const next = source[index + 1] ?? "";
      if (stopAtClosingBrace && character === "}" && braceDepth === 0) {
        return index;
      }
      if (character === "/" && next === "/") {
        index += 2;
        while (index < source.length && (source[index] ?? "") !== "\n") {
          index += 1;
        }
        continue;
      }
      if (character === "/" && next === "*") {
        index += 2;
        while (index < source.length) {
          if (
            (source[index] ?? "") === "*" &&
            (source[index + 1] ?? "") === "/"
          ) {
            index += 2;
            break;
          }
          index += 1;
        }
        continue;
      }
      if (character === "/" && regexStart(index)) {
        index = skipRegex(index);
        continue;
      }
      if (character === '"' || character === "'") {
        index = skipQuoted(index, character);
        continue;
      }
      if (character === "`") {
        index = scanTemplate(index);
        continue;
      }

      reveal(index);
      if (stopAtClosingBrace && character === "{") braceDepth += 1;
      if (stopAtClosingBrace && character === "}") braceDepth -= 1;
      index += 1;
    }
    return index;
  };

  scanTemplate = (start: number): number => {
    let index = start + 1;
    while (index < source.length) {
      const character = source[index] ?? "";
      const next = source[index + 1] ?? "";
      if (character === "\\") {
        index += 2;
        continue;
      }
      if (character === "`") return index + 1;
      if (character === "$" && next === "{") {
        reveal(index);
        reveal(index + 1);
        const closingBrace = scanCode(index + 2, true);
        if ((source[closingBrace] ?? "") === "}") {
          reveal(closingBrace);
          index = closingBrace + 1;
        } else {
          index = closingBrace;
        }
        continue;
      }
      index += 1;
    }
    return index;
  };

  scanCode(0, false);
  return output.join("");
}

async function checkFile(file: string): Promise<void> {
  const bunFile = Bun.file(file);
  if (!(await bunFile.exists())) {
    fail(file, "file not found");
    return;
  }
  const source = await bunFile.text();

  // F7 — .sh files run ONLY the BG0 shim-marker check; none of the TS checks below apply.
  if (file.endsWith(".sh")) {
    checkShellFile(file, source);
    return;
  }

  const lines = source.split("\n");
  const code = codeLines(source);
  const executable = executableCode(source);

  // F1 / W8 — shebang policy
  const shebang = lines[0]?.startsWith("#!") ? lines[0] : undefined;
  if (shebang !== undefined) {
    if (shebang.includes("node")) {
      fail(
        file,
        "shebang names node — bun honors it and executes node; use env bun or none (BG1)",
      );
    } else {
      warn(
        file,
        "shebang present — legal only on a binary-substituted fixture (BG1); ordinary scripts run `bun <path>`",
      );
    }
  }

  // F2 — CJS require
  // (messages below avoid the literal token sequences the detectors grep for,
  //  so this floor stays clean when run over its own source)
  if (/\brequire\s*\(/.test(code)) {
    fail(file, "CommonJS require — house scripts are ESM only (BG1)");
  }

  // F3 — import specifiers (static, side-effect, and dynamic incl. backtick literals)
  for (const match of code.matchAll(IMPORT_SPECIFIER)) {
    const spec = match[1] ?? match[2] ?? match[3];
    if (spec === undefined) continue;
    const kind = classifySpecifier(spec);
    if (kind === "bare") {
      const zeroDep = zeroDepReason(file);
      const graduation = zeroDep === null ? findGraduation(file) : null;
      const declared = graduation?.deps.get(spec);
      if (zeroDep !== null) {
        fail(
          file,
          `external dependency '${spec}' in a zero-dep tree — ${zeroDep} (BG3), graduation project or not`,
        );
      } else if (declared === undefined) {
        fail(
          file,
          `unpinned external dependency '${spec}' — BG3 ladder: builtin, pinned ${BUNX}, or graduate (no governing package.json+bun.lock declares it)`,
        );
      } else if (!EXACT_VERSION.test(declared)) {
        fail(
          file,
          `'${spec}' is declared as '${declared}' in ${graduation?.root}/package.json — a range is not a pin (PINNED-OR-ABSENT); use an exact version`,
        );
      }
    } else if (kind === "pinned") {
      warn(
        file,
        `pinned inline dependency '${spec}' — throws under any ancestor node_modules (facts §4); known-clean-cwd one-offs only`,
      );
    }
  }
  if (COMPUTED_DYNAMIC_IMPORT.test(code)) {
    warn(
      file,
      "dynamic import with a computed specifier — floor cannot classify it; BG3 by hand",
    );
  }

  // F8 / F5 — ordinary Bun CLI boundaries use Cleye. Its strictFlags check happens after
  // type-flag has assigned unknowns, so the local ignoreArgv guard rejects __proto__ first.
  // Cleye command options inherit strictFlags but NOT ignoreArgv, hence each command is a
  // separately guarded boundary. Direct typeFlag is reserved for the marked raw-forwarding
  // exception, whose relay's token/order/`--` behavior remains a reviewer responsibility.
  const parseArgsCall = new RegExp(`\\b${"parse" + "Args"}\\s*\\(`);
  const argvReads = executable.match(/\b(?:Bun|process)\.argv\b/g)?.length ?? 0;
  const typeFlagCalls = executable.match(/\btypeFlag\s*\(/g)?.length ?? 0;
  const cleyeImportSpecifiers = [
    ...code.matchAll(/\bimport\s*{([^}]*)}\s*from\s+["']cleye["']/gs),
  ].flatMap((match) =>
    (match[1] ?? "")
      .split(",")
      .map((specifier) => specifier.trim())
      .filter((specifier) => specifier.length > 0),
  );
  // Alias policy: only exact `{ cli, command }` bindings are house Cleye boundaries.
  // Aliases fail explicitly; coincidentally named local/domain helpers are never counted.
  const importsCleyeCli = cleyeImportSpecifiers.includes("cli");
  const importsCleyeCommand = cleyeImportSpecifiers.includes("command");
  const aliasedCleyeBoundary = cleyeImportSpecifiers.find((specifier) =>
    /^(?:cli|command)\s+as\s+/.test(specifier),
  );
  const cliCalls = importsCleyeCli
    ? (executable.match(/\bcli\s*\(/g)?.length ?? 0)
    : 0;
  const commandCalls = importsCleyeCommand
    ? (executable.match(/\bcommand\s*\(/g)?.length ?? 0)
    : 0;
  const cleyeBoundaries = cliCalls + commandCalls;
  const forwarding =
    /^\s*\/\/\s*argv-forwarding:\s*[A-Za-z0-9_.:/-]+\s*$/m.test(source);
  if (parseArgsCall.test(executable)) {
    fail(
      file,
      "node:util parseArgs is forbidden — ordinary Bun CLIs use Cleye cli() (BG1)",
    );
  }
  if (aliasedCleyeBoundary !== undefined) {
    const binding =
      aliasedCleyeBoundary.split(/\s+/)[0] ?? aliasedCleyeBoundary;
    fail(
      file,
      `import Cleye ${binding} with its exact \`${binding}\` binding — aliases are outside the lexical floor contract (BG1)`,
    );
  }
  if (typeFlagCalls > 0 && !forwarding) {
    fail(
      file,
      "direct type-flag needs an exact argv-forwarding marker — ordinary Bun CLIs use Cleye (BG1)",
    );
  }
  if (forwarding && typeFlagCalls === 0) {
    fail(
      file,
      "argv-forwarding marker has no direct type-flag use — exceptions must parse the wrapper boundary (BG1)",
    );
  }
  if (forwarding && cleyeBoundaries > 0) {
    fail(
      file,
      "argv-forwarding exception mixes direct type-flag with Cleye — choose one boundary (BG1)",
    );
  }
  if (forwarding) {
    const ignoreCallbacks =
      executable.match(/\bignore\s*:\s*(?!undefined\b)/g)?.length ?? 0;
    if (ignoreCallbacks < typeFlagCalls) {
      fail(
        file,
        `argv-forwarding wrapper has ${typeFlagCalls} typeFlag() call(s) but only ${ignoreCallbacks} ignore callback(s) — preserve downstream argv before parser assignment (BG1)`,
      );
    }
    if (!/\bunknownFlags\b/.test(code)) {
      fail(
        file,
        "argv-forwarding type-flag use lacks an unknownFlags invariant — retain the defensive wrapper check (BG1)",
      );
    }
  }
  if (argvReads > 0 && cleyeBoundaries === 0 && !forwarding) {
    fail(file, "Bun.argv/process.argv read without a Cleye boundary (BG1)");
  } else if (!forwarding && argvReads > cliCalls) {
    fail(
      file,
      `more argv reads than Cleye calls (${argvReads}/${cliCalls}) — parse positionals through the same schema; do not reopen argv (BG1)`,
    );
  }
  if (cleyeBoundaries > 0) {
    const strictFlags =
      executable.match(/\bstrictFlags\s*:\s*true\b/g)?.length ?? 0;
    if (strictFlags < cleyeBoundaries) {
      fail(
        file,
        `Cleye has ${cleyeBoundaries} cli()/command() boundary(s) but only ${strictFlags} strictFlags: true declaration(s) — ordinary unknown flags must fail (BG1)`,
      );
    }
    const prototypeGuards =
      executable.match(/\bignoreArgv\s*:\s*rejectPrototypeFlag\b/g)?.length ??
      0;
    if (prototypeGuards < cleyeBoundaries) {
      fail(
        file,
        `Cleye has ${cleyeBoundaries} boundary(s) but only ${prototypeGuards} ignoreArgv: rejectPrototypeFlag declaration(s) — strictFlags alone misses '--__proto__' before type-flag mutation (BG1)`,
      );
    }
    const parameterSchemas = executable.match(/\bparameters\s*:/g)?.length ?? 0;
    if (parameterSchemas < cleyeBoundaries) {
      fail(
        file,
        `Cleye has ${cleyeBoundaries} boundary(s) but only ${parameterSchemas} parameters: declaration(s) — spell parameters: [] for flag-only CLIs so excess positionals are intentional (BG1)`,
      );
    }
    const hasSpreadParameters = /\bparameters\s*:\s*\[[^\]]*\.\.\./s.test(code);
    const explicitExcessRefusal =
      /\b_\s*\.\s*length\b/.test(executable) ||
      /\brejectUnexpectedArguments\s*\(\s*[\w.]+\.unknownFlags\s*,\s*[\w.]+\._\s*\)/.test(
        executable,
      );
    if (!hasSpreadParameters && !explicitExcessRefusal) {
      fail(
        file,
        "non-spread Cleye parameters need a parsed._.length or rejectUnexpectedArguments(parsed.unknownFlags, parsed._) excess refusal — Cleye otherwise leaves extras in the array (BG1)",
      );
    }
  }

  if (typeFlagCalls > 0) {
    // F6 — a camelCase schema key silently becomes a SECOND accepted CLI spelling: declaring
    // `dryRun` makes both `--dry-run` and `--dryRun` valid, widening the contract compared with
    // parseArgs, which accepted only what was declared. Declaring the key in kebab removes the
    // alias entirely (measured 2026-07-28), and the unknownFlags guard then rejects it.
    // Heuristic: object keys immediately followed by `{ type:` or a built-in parser
    // constructor anywhere in a parser-using file.
    const schemaKey =
      /(?:^|[,{])\s*([A-Za-z_$][A-Za-z0-9_$]*)\s*:\s*(?:\{\s*type\s*:|(?:Boolean|String|Number)\b)/gm;
    for (const match of code.matchAll(schemaKey)) {
      const key = match[1] ?? "";
      if (/[a-z][A-Z]/.test(key)) {
        const kebabKey = key.replace(
          /[A-Z]/g,
          (character) => `-${character.toLowerCase()}`,
        );
        fail(
          file,
          `typed-parser schema key '${key}' is camelCase — it also registers '--${key}' as a valid flag, widening the CLI contract; declare it as the kebab spelling ('${kebabKey}') instead`,
        );
      }
    }

    // F13 — String turns a present flag with no value into the empty string. Requiring a
    // throwing parser makes missing-value behavior explicit at the boundary. This broad
    // schema-shaped regex is intentionally a floor; a false positive gets hand-reviewed.
    const rawStringFlag =
      /(?:^|[,{])\s*(?:["'][^"']+["']|[A-Za-z_$][A-Za-z0-9_$-]*)\s*:\s*(?:\{\s*type\s*:\s*)?(?:\[\s*)?String(?:\s*\])?(?![A-Za-z0-9_$(])/gm;
    if (rawStringFlag.test(code)) {
      fail(
        file,
        "raw String flag parser — a present option with no value becomes ''; use a throwing non-empty parser (BG1)",
      );
    }

    // W11 — a malformed Number lands as null rather than throwing.
    if (
      /type:\s*Number\b/.test(code) &&
      !/===\s*null|!==\s*null|\?\?|Number\.isFinite/.test(code)
    ) {
      warn(
        file,
        "typed-parser Number flag with no null/finite check — malformed input coerces to null, not a throw; validate before use",
      );
    }
  }

  // F4 — string-shell exec
  if (/child_process/.test(code) && /\b(?:exec|execSync)\s*\(/.test(code)) {
    fail(
      file,
      "child_process exec/execSync — string shell; use Bun.$ or spawn array-form (BG2)",
    );
  }

  // W5 — per-call: spawn with no timeout:/signal: in its window and no bounded note beside
  // it. Scans SOURCE (not stripped code): the bounded note IS a comment; cost is that a
  // spawn call inside a block comment can still WARN — acceptable floor noise.
  let unbounded = 0;
  const spawnAt = [...source.matchAll(/Bun\.spawn(?:Sync)?\s*\(/g)].map(
    (m) => m.index ?? 0,
  );
  spawnAt.forEach((at, i) => {
    const end = Math.min(at + 400, spawnAt[i + 1] ?? source.length);
    const window = source.slice(at, end);
    // shorthand `signal,` / `signal }` counts: the house AbortSignal idiom passes a
    // shorthand property, not `signal:`
    if (
      /\b(?:timeout\s*:|maxBuffer\s*:|killSignal\s*:|signal\s*[:,}])/.test(
        window,
      )
    )
      return;
    const before = source.slice(Math.max(0, at - 200), at);
    if (BOUNDED_NOTE.test(before) || BOUNDED_NOTE.test(window)) return;
    unbounded += 1;
  });
  if (unbounded > 0) {
    warn(
      file,
      `${unbounded} spawn call(s) without timeout:/signal: or a \`// bounded: <reason>\` beside the call — hangable? (BG2)`,
    );
  }

  // W6 — hand-rolled timeout+kill where a native option exists
  if (/setTimeout\s*\(/.test(code) && /\.kill\s*\(/.test(code)) {
    warn(
      file,
      "hand-rolled setTimeout+kill — native Bun.spawn timeout:/killSignal: exists (facts §3, REFACTOR)",
    );
  }

  // W7 — bunx without any visible version pin
  if (BUNX_PATTERN.test(executable) && !/@\d/.test(executable)) {
    warn(
      file,
      `${BUNX} call with no visible @x.y.z pin — ${BUNX} staleness is real (facts §5)`,
    );
  }

  // W9 — the kill flag read as a kill/timeout detector. It is true after a CLEAN exit too, so
  // a branch on it fires on every run and misreports success as a timeout (facts §3, measured).
  // Token split so this file's own source does not trip the scan (self-scan guard, as BUNX).
  if (new RegExp(`\\.${KILLED}\\b`).test(code)) {
    warn(
      file,
      `\`.${KILLED}\` present — it is true after a clean exit; bound with AbortSignal.timeout and read \`sig.aborted\` (facts §3)`,
    );
  }

  // W10 — sequential drain of a child's two pipes. Awaiting stdout to completion and THEN
  // stderr deadlocks the moment the child fills the pipe nobody is reading; the symptom is
  // your own timeout firing, which reads as "the child is slow" (facts §3).
  const drainsStdout = /new Response\(\s*[\w.]*\.stdout\s*\)/.test(code);
  const drainsStderr = /new Response\(\s*[\w.]*\.stderr\s*\)/.test(code);
  if (drainsStdout && drainsStderr && !/Promise\.all/.test(code)) {
    warn(
      file,
      "drains .stdout and .stderr but no Promise.all — sequential drain deadlocks on a full pipe (facts §3)",
    );
  }
}

function rejectPrototypeFlag(
  type: "known-flag" | "unknown-flag" | "argument",
  flag: string,
): void {
  if (type === "unknown-flag" && flag === "__proto__") {
    throw new Error("refusing prototype-mutating option '--__proto__'");
  }
}

async function main(): Promise<void> {
  await cli(
    {
      name: "script-check",
      parameters: ["<file...>"],
      strictFlags: true,
      ignoreArgv: rejectPrototypeFlag,
      help: {
        description:
          "Check house Bun script structure. Pass one or more .ts or .sh files.",
      },
    },
    async ({ _: { file: files } }) => {
      for (const file of files) await checkFile(file);
      process.stdout.write(
        `floor: FAIL=${failures} WARN=${warnings} (files=${files.length}) — structure only; BG1-BG4 judgment is not covered\n`,
      );
      process.exitCode = failures === 0 ? 0 : 1;
    },
    Bun.argv.slice(2),
  );
}

main().catch((error) => {
  process.stderr.write(
    `FATAL: ${error instanceof Error ? error.message : String(error)}\n`,
  );
  process.exitCode = 2;
});
