// script-check.ts — mechanical floor for house Bun TypeScript scripts (writing-bun-scripts).
// Run: bun script-check.ts <file.ts|file.sh ...>   Consumer: agent (verdict lines).
// Exit: 0 clean (WARNs allowed — they inform, they do not gate) / 1 any FAIL / 2 fatal.
//
// THIS IS NOT A SEMANTIC CHECK. It greps structure only, with declared heuristics
// (per-call windows, line-based comment stripping). It cannot judge: whether the declared
// consumer/envelope is right, exit-code discipline, whether a bash shim was classified
// correctly, timeout values, or test adequacy — those are BG1–BG4 judgment.
//
// A `.sh` path skips every TS check below and runs ONLY the BG0 shim-marker check.
//
// Checks (owner: writing-bun-scripts SKILL.md gates; facts: references/bun-facts.md):
//   F1  node shebang            — bun honors `#!/usr/bin/env node` and would exec node
//   W8  any other shebang       — BG1: shebang only on binary-substituted fixtures
//   F2  CommonJS require        — scripts are ESM only (top-level await incompatible)
//   F3  external import         — bare import FAIL unless an ancestor package.json+bun.lock
//                                 (BG3 graduation, resolved on the file's REALPATH) declares it
//                                 at an EXACT version; ALWAYS FAIL inside hooks/ (they run
//                                 before any install); pinned inline import WARN (cwd trap);
//                                 computed dynamic WARN
//   F5  typed parser unguarded  — typeFlag() without pre-assignment unknown rejection plus
//                                 the post-parse unknownFlags invariant
//   F8  untyped argv parsing    — parseArgs(), or Bun/process argv read without the approved
//                                 type-flag boundary; extra argv reads are rejected
//   W11 typed-parser Number     — a Number flag with no null check: bad input yields null, not
//                                 a throw, so the failure is silent
//   F13 raw String flag parser  — missing flag values become ""; use a throwing parser
//   F4  child_process exec()    — string-shell; use Bun.$ or spawn array-form
//   W5  unbounded spawn         — per-call: no timeout:/signal: in the call window and no
//                                 `// bounded: <reason>` beside it
//   W6  setTimeout + kill       — hand-rolled timeout; native Bun.spawn timeout: exists
//   W7  unpinned bunx           — bunx staleness is real; pin pkg@x.y.z
//   W9  .killed as detector     — true after a clean exit; use AbortSignal.timeout + aborted
//   W10 sequential pipe drain   — stdout-then-stderr deadlocks; drain via Promise.all
//   F7  .sh with no shim marker — BG0: a surviving `.sh` carries `# shim: <class>` or is
//                                 content-detected `vendored` (an external tool's own header)

import { existsSync, readFileSync, realpathSync } from "node:fs";
import { dirname, join } from "node:path";
import { typeFlag } from "type-flag";

let failures = 0;
let warnings = 0;

function fail(file: string, message: string): void {
  process.stdout.write(`FAIL ${file}: ${message}\n`);
  failures += 1;
}

function warn(file: string, message: string): void {
  process.stdout.write(`WARN ${file}: ${message}\n`);
  warnings += 1;
}

// Split tokens so this file's own source does not trip its own scans (self-scan guard).
const BUNX = "bun" + "x";
const KILLED = "kill" + "ed";
const BUNX_PATTERN = new RegExp(`\\b${BUNX}\\b`);

// --- F7: BG0 shim marker for surviving .sh files -------------------------------------------
// A `# shim: <class>` comment line, any of the four declared classes. `vendored` is the one
// EXEMPT class: its own tool overwrites the file, so a written marker would not survive —
// exemption is read from the file's OWN CONTENT (a vendor header), never a path allowlist.
const SHIM_CLASSES = [
  "bootstrap",
  "hook-entry",
  "exec-wrapper",
  "vendored",
] as const;
const SHIM_LINE = /^\s*#\s*shim:\s*(\S+)\s*$/m;
const VENDOR_HEADER =
  /\b(?:managed by|generated by|installed by|auto-?generated|do not edit)\b/i;

function checkShellFile(file: string, source: string): void {
  // .match(), not RegExp.prototype.exec() — the literal token "exec(" would trip this
  // file's own F4 self-scan (it shares the file with an unrelated `child_process` mention).
  const match = source.match(SHIM_LINE);
  if (match) {
    const declared = match[1] ?? "";
    if ((SHIM_CLASSES as readonly string[]).includes(declared)) return;
    fail(
      file,
      `'# shim: ${declared}' is not a declared class (${SHIM_CLASSES.join("|")}) (BG0)`,
    );
    return;
  }
  if (VENDOR_HEADER.test(source)) {
    warn(
      file,
      "no `# shim:` marker, but a vendor header was detected — treated as the vendored exemption (BG0); a written marker would not survive the tool's own overwrite",
    );
    return;
  }
  fail(
    file,
    `no \`# shim: <${SHIM_CLASSES.join("|")}>\` marker (BG0) — a surviving .sh needs a declared shim class, or a vendor header if the exemption applies`,
  );
}

const IMPORT_SPECIFIER =
  /(?:^|\s)(?:import|export)\s+[^"'()]*?from\s+["']([^"']+)["']|(?:^|\s)import\s+["']([^"']+)["']|import\s*\(\s*["'`]([^"'`$]+)["'`]\s*\)/g;
const COMPUTED_DYNAMIC_IMPORT = /import\s*\(\s*(?:`[^`]*\$\{|[A-Za-z_$])/;
const BOUNDED_NOTE = /\/\/\s*bounded:\s*\S/;

function classifySpecifier(
  spec: string,
): "builtin" | "relative" | "pinned" | "bare" {
  if (spec.startsWith("node:") || spec.startsWith("bun:") || spec === "bun")
    return "builtin";
  if (spec.startsWith(".") || spec.startsWith("/")) return "relative";
  // pinned: name@range or @scope/name@range (an @ after the first character)
  return spec.slice(1).includes("@") ? "pinned" : "bare";
}

// --- BG3 graduation resolution -------------------------------------------------------------
// A bare specifier is legal when a graduation project GOVERNS the file: the nearest ancestor
// package.json (walking the file's REALPATH, because skills are symlinked into ~/.claude/skills
// and Bun resolves through the link) that has a sibling bun.lock, declaring the dep at an EXACT
// version. A range pin (^ ~ * x) is not a pin — PINNED-OR-ABSENT.
type Graduation = { root: string; deps: Map<string, string> };
const graduationCache = new Map<string, Graduation | null>();

function findGraduation(fromFile: string): Graduation | null {
  let directory = dirname(realpathSync(fromFile));
  const seen: string[] = [];
  for (;;) {
    const cached = graduationCache.get(directory);
    if (cached !== undefined) {
      for (const d of seen) graduationCache.set(d, cached);
      return cached;
    }
    seen.push(directory);
    const manifest = join(directory, "package.json");
    if (existsSync(manifest) && existsSync(join(directory, "bun.lock"))) {
      let deps = new Map<string, string>();
      try {
        const parsed = JSON.parse(readFileSync(manifest, "utf8")) as {
          dependencies?: Record<string, string>;
          devDependencies?: Record<string, string>;
        };
        deps = new Map(
          Object.entries({ ...parsed.dependencies, ...parsed.devDependencies }),
        );
      } catch {
        deps = new Map();
      }
      const found: Graduation = { root: directory, deps };
      for (const d of seen) graduationCache.set(d, found);
      return found;
    }
    const parent = dirname(directory);
    if (parent === directory) break;
    directory = parent;
  }
  for (const d of seen) graduationCache.set(d, null);
  return null;
}

const EXACT_VERSION = /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/;

// A graduation project licenses bare imports only for code that STAYS inside it. Two classes
// leave and must remain zero-dep, because where they run there is no lockfile and no install:
//   1. hooks/ — run on every harness event, before any `mise run deps` on this machine;
//   2. any tree marked with a `.zero-dep` file — skills that are mirrored, persisted, or
//      degit-copied into other people's repos, and `templates/` shipped into deliverables.
// The marker is the escape hatch for (2) because "does this get distributed?" is not something
// a floor can infer from a path.
function zeroDepReason(file: string): string | null {
  const path = realpathSync(file).replaceAll("\\", "/");
  if (/(^|\/)(hooks|templates)\//.test(path)) {
    return "it lives under hooks/ or templates/ — that code runs where no install has happened";
  }
  let directory = dirname(path);
  for (;;) {
    if (existsSync(join(directory, ".zero-dep"))) {
      return `${directory}/.zero-dep marks this tree as distributed — it runs outside this repo's lockfile`;
    }
    const parent = dirname(directory);
    if (parent === directory) return null;
    directory = parent;
  }
}

// Line-based comment stripping: drops // lines and /* ... */ block interiors (heuristic —
// a string literal containing comment markers can confuse it; acceptable for a floor).
function codeLines(source: string): string {
  const kept: string[] = [];
  let inBlock = false;
  for (const line of source.split("\n")) {
    let text = line;
    if (inBlock) {
      const close = text.indexOf("*/");
      if (close === -1) continue;
      text = text.slice(close + 2);
      inBlock = false;
    }
    if (/^\s*\/\//.test(text)) continue;
    const open = text.indexOf("/*");
    if (open !== -1 && !text.slice(open + 2).includes("*/")) {
      text = text.slice(0, open);
      inBlock = true;
    }
    kept.push(text);
  }
  return kept.join("\n");
}

// F8 needs executable tokens, not examples embedded in diagnostics or tests. This is deliberately
// a lexical floor rather than a TS parser: quoted strings are blanked after comment stripping.
function executableCode(source: string): string {
  return codeLines(source)
    .replace(/`(?:\\.|[^`\\])*`/gs, "``")
    .replace(/"(?:\\.|[^"\\])*"/g, '""')
    .replace(/'(?:\\.|[^'\\])*'/g, "''");
}

async function checkFile(file: string): Promise<void> {
  const bunFile = Bun.file(file);
  if (!(await bunFile.exists())) {
    fail(file, "file not found");
    return;
  }
  const source = await bunFile.text();

  // F7 — .sh files run ONLY the BG0 shim-marker check; none of the TS checks below apply.
  if (file.endsWith(".sh")) {
    checkShellFile(file, source);
    return;
  }

  const lines = source.split("\n");
  const code = codeLines(source);
  const executable = executableCode(source);

  // F1 / W8 — shebang policy
  const shebang = lines[0]?.startsWith("#!") ? lines[0] : undefined;
  if (shebang !== undefined) {
    if (shebang.includes("node")) {
      fail(
        file,
        "shebang names node — bun honors it and executes node; use env bun or none (BG1)",
      );
    } else {
      warn(
        file,
        "shebang present — legal only on a binary-substituted fixture (BG1); ordinary scripts run `bun <path>`",
      );
    }
  }

  // F2 — CJS require
  // (messages below avoid the literal token sequences the detectors grep for,
  //  so this floor stays clean when run over its own source)
  if (/\brequire\s*\(/.test(code)) {
    fail(file, "CommonJS require — house scripts are ESM only (BG1)");
  }

  // F3 — import specifiers (static, side-effect, and dynamic incl. backtick literals)
  for (const match of code.matchAll(IMPORT_SPECIFIER)) {
    const spec = match[1] ?? match[2] ?? match[3];
    if (spec === undefined) continue;
    const kind = classifySpecifier(spec);
    if (kind === "bare") {
      const zeroDep = zeroDepReason(file);
      const graduation = zeroDep === null ? findGraduation(file) : null;
      const declared = graduation?.deps.get(spec);
      if (zeroDep !== null) {
        fail(
          file,
          `external dependency '${spec}' in a zero-dep tree — ${zeroDep} (BG3), graduation project or not`,
        );
      } else if (declared === undefined) {
        fail(
          file,
          `unpinned external dependency '${spec}' — BG3 ladder: builtin, pinned ${BUNX}, or graduate (no governing package.json+bun.lock declares it)`,
        );
      } else if (!EXACT_VERSION.test(declared)) {
        fail(
          file,
          `'${spec}' is declared as '${declared}' in ${graduation?.root}/package.json — a range is not a pin (PINNED-OR-ABSENT); use an exact version`,
        );
      }
    } else if (kind === "pinned") {
      warn(
        file,
        `pinned inline dependency '${spec}' — throws under any ancestor node_modules (facts §4); known-clean-cwd one-offs only`,
      );
    }
  }
  if (COMPUTED_DYNAMIC_IMPORT.test(code)) {
    warn(
      file,
      "dynamic import with a computed specifier — floor cannot classify it; BG3 by hand",
    );
  }

  // F8 — every kept Bun CLI crosses the type-flag boundary. `parseArgs`, Cleye, and direct
  // argv reads were previously invisible to this floor. Counting reads closes the common
  // evasion where one legitimate typeFlag() call is followed by a second hand-parsed read.
  const parseArgsCall = new RegExp(`\\b${"parse" + "Args"}\\s*\\(`);
  const argvReads = executable.match(/\b(?:Bun|process)\.argv\b/g)?.length ?? 0;
  const typeFlagCalls = executable.match(/\btypeFlag\s*\(/g)?.length ?? 0;
  const usesTypeFlag = typeFlagCalls > 0;
  const importsCleye = /\bfrom\s+["']cleye["']/.test(code);
  if (parseArgsCall.test(executable)) {
    fail(
      file,
      "node:util parseArgs is forbidden — kept Bun CLIs use typeFlag() (BG1)",
    );
  }
  if (importsCleye) {
    fail(
      file,
      "Cleye is outside the house argv boundary — kept Bun CLIs use typeFlag() without exception (BG1)",
    );
  }
  if (argvReads > 0 && typeFlagCalls === 0) {
    fail(
      file,
      "Bun.argv/process.argv read without the typeFlag() boundary (BG1)",
    );
  } else if (argvReads > typeFlagCalls) {
    fail(
      file,
      `more argv reads than typeFlag() calls (${argvReads}/${typeFlagCalls}) — parse positionals from the same result; do not reopen argv (BG1)`,
    );
  }

  // F5 — reject unknown names inside type-flag's `ignore` callback, before its ordinary
  // object-backed unknownFlags table is mutated. A post-parse Object.keys() guard alone can
  // miss the magic `__proto__` name. Forwarding wrappers are the one explicit exception:
  // their marker says which downstream tool owns unknown argv, and their ignore callback
  // must keep those tokens out of the table. In both modes unknownFlags remains a checked
  // post-parse invariant.
  if (usesTypeFlag) {
    const forwarding = /\/\/\s*argv-forwarding:\s*[A-Za-z0-9_.:/-]+\s*$/m.test(
      source,
    );
    if (forwarding) {
      const ignoreCallbacks =
        executable.match(/\bignore\s*:\s*(?!undefined\b)/g)?.length ?? 0;
      if (ignoreCallbacks < typeFlagCalls) {
        fail(
          file,
          `argv-forwarding wrapper has ${typeFlagCalls} typeFlag() call(s) but only ${ignoreCallbacks} ignore callback(s) — explicitly preserve downstream unknown flags before table assignment (BG1)`,
        );
      }
    } else {
      const earlyRejectors =
        executable.match(/\bignore\s*:\s*rejectUnknownFlag\b/g)?.length ?? 0;
      if (earlyRejectors < typeFlagCalls) {
        fail(
          file,
          `typeFlag() without an early \`ignore: rejectUnknownFlag\` interceptor (${earlyRejectors}/${typeFlagCalls}) — Object.keys(unknownFlags) alone misses '--__proto__' (BG1)`,
        );
      }
    }
    if (!/\bunknownFlags\b/.test(code)) {
      fail(
        file,
        "typeFlag() without a post-parse unknownFlags invariant — retain the defensive guard after early rejection (BG1)",
      );
    }
    // F6 — a camelCase schema key silently becomes a SECOND accepted CLI spelling: declaring
    // `dryRun` makes both `--dry-run` and `--dryRun` valid, widening the contract compared with
    // parseArgs, which accepted only what was declared. Declaring the key in kebab removes the
    // alias entirely (measured 2026-07-28), and the unknownFlags guard then rejects it.
    // Heuristic: object keys immediately followed by `{ type:` or a built-in parser
    // constructor anywhere in a parser-using file.
    const schemaKey =
      /(?:^|[,{])\s*([A-Za-z_$][A-Za-z0-9_$]*)\s*:\s*(?:\{\s*type\s*:|(?:Boolean|String|Number)\b)/gm;
    for (const match of code.matchAll(schemaKey)) {
      const key = match[1] ?? "";
      if (/[a-z][A-Z]/.test(key)) {
        fail(
          file,
          `typed-parser schema key '${key}' is camelCase — it also registers '--${key}' as a valid flag, widening the CLI contract; declare it as the kebab spelling ('${key.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`)}') instead`,
        );
      }
    }

    // F13 — String turns a present flag with no value into the empty string. Requiring a
    // throwing parser makes missing-value behavior explicit at the boundary. This broad
    // schema-shaped regex is intentionally a floor; a false positive gets hand-reviewed.
    const rawStringFlag =
      /(?:^|[,{])\s*(?:["'][^"']+["']|[A-Za-z_$][A-Za-z0-9_$-]*)\s*:\s*(?:\{\s*type\s*:\s*)?(?:\[\s*)?String(?:\s*\])?(?![A-Za-z0-9_$(])/gm;
    if (rawStringFlag.test(code)) {
      fail(
        file,
        "raw String flag parser — a present option with no value becomes ''; use a throwing non-empty parser (BG1)",
      );
    }

    // W11 — a malformed Number lands as null rather than throwing.
    if (
      /type:\s*Number\b/.test(code) &&
      !/===\s*null|!==\s*null|\?\?|Number\.isFinite/.test(code)
    ) {
      warn(
        file,
        "typed-parser Number flag with no null/finite check — malformed input coerces to null, not a throw; validate before use",
      );
    }
  }

  // F4 — string-shell exec
  if (/child_process/.test(code) && /\b(?:exec|execSync)\s*\(/.test(code)) {
    fail(
      file,
      "child_process exec/execSync — string shell; use Bun.$ or spawn array-form (BG2)",
    );
  }

  // W5 — per-call: spawn with no timeout:/signal: in its window and no bounded note beside
  // it. Scans SOURCE (not stripped code): the bounded note IS a comment; cost is that a
  // spawn call inside a block comment can still WARN — acceptable floor noise.
  let unbounded = 0;
  const spawnAt = [...source.matchAll(/Bun\.spawn(?:Sync)?\s*\(/g)].map(
    (m) => m.index ?? 0,
  );
  spawnAt.forEach((at, i) => {
    const end = Math.min(at + 400, spawnAt[i + 1] ?? source.length);
    const window = source.slice(at, end);
    // shorthand `signal,` / `signal }` counts: the house AbortSignal idiom passes a
    // shorthand property, not `signal:`
    if (
      /\b(?:timeout\s*:|maxBuffer\s*:|killSignal\s*:|signal\s*[:,}])/.test(
        window,
      )
    )
      return;
    const before = source.slice(Math.max(0, at - 200), at);
    if (BOUNDED_NOTE.test(before) || BOUNDED_NOTE.test(window)) return;
    unbounded += 1;
  });
  if (unbounded > 0) {
    warn(
      file,
      `${unbounded} spawn call(s) without timeout:/signal: or a \`// bounded: <reason>\` beside the call — hangable? (BG2)`,
    );
  }

  // W6 — hand-rolled timeout+kill where a native option exists
  if (/setTimeout\s*\(/.test(code) && /\.kill\s*\(/.test(code)) {
    warn(
      file,
      "hand-rolled setTimeout+kill — native Bun.spawn timeout:/killSignal: exists (facts §3, REFACTOR)",
    );
  }

  // W7 — bunx without any visible version pin
  if (BUNX_PATTERN.test(code) && !/@\d/.test(code)) {
    warn(
      file,
      `${BUNX} call with no visible @x.y.z pin — ${BUNX} staleness is real (facts §5)`,
    );
  }

  // W9 — the kill flag read as a kill/timeout detector. It is true after a CLEAN exit too, so
  // a branch on it fires on every run and misreports success as a timeout (facts §3, measured).
  // Token split so this file's own source does not trip the scan (self-scan guard, as BUNX).
  if (new RegExp(`\\.${KILLED}\\b`).test(code)) {
    warn(
      file,
      `\`.${KILLED}\` present — it is true after a clean exit; bound with AbortSignal.timeout and read \`sig.aborted\` (facts §3)`,
    );
  }

  // W10 — sequential drain of a child's two pipes. Awaiting stdout to completion and THEN
  // stderr deadlocks the moment the child fills the pipe nobody is reading; the symptom is
  // your own timeout firing, which reads as "the child is slow" (facts §3).
  const drainsStdout = /new Response\(\s*[\w.]*\.stdout\s*\)/.test(code);
  const drainsStderr = /new Response\(\s*[\w.]*\.stderr\s*\)/.test(code);
  if (drainsStdout && drainsStderr && !/Promise\.all/.test(code)) {
    warn(
      file,
      "drains .stdout and .stderr but no Promise.all — sequential drain deadlocks on a full pipe (facts §3)",
    );
  }
}

function rejectUnknownFlag(
  type: "known-flag" | "unknown-flag" | "argument",
  flag: string,
): void {
  if (type === "unknown-flag") {
    throw new Error(`unknown option '--${flag}'`);
  }
}

async function main(): Promise<void> {
  const parsed = typeFlag({}, Bun.argv.slice(2), {
    ignore: rejectUnknownFlag,
  });
  const unknownFlag = Object.keys(parsed.unknownFlags)[0];
  if (unknownFlag !== undefined) {
    throw new Error(`unknown option '--${unknownFlag}'`);
  }
  const files = parsed._;
  if (files.length === 0) {
    throw new Error("usage: bun script-check.ts <file.ts|file.sh ...>");
  }
  for (const file of files) await checkFile(file);
  process.stdout.write(
    `floor: FAIL=${failures} WARN=${warnings} (files=${files.length}) — structure only; BG1-BG4 judgment is not covered\n`,
  );
  process.exitCode = failures === 0 ? 0 : 1;
}

main().catch((error) => {
  process.stderr.write(
    `FATAL: ${error instanceof Error ? error.message : String(error)}\n`,
  );
  process.exitCode = 2;
});
